[2023-03-25T14:05:46.946-0400] {processor.py:153} INFO - Started process (PID=7703) to work on /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:05:46.948-0400] {processor.py:743} INFO - Processing file /Users/sunanda/airflow/dags/weatherapi_test.py for tasks to queue
[2023-03-25T14:05:46.948-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:05:46.948-0400] {dagbag.py:532} INFO - Filling up the DagBag from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:05:46.982-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:05:46.975-0400] {dagbag.py:341} ERROR - Failed to import: /Users/sunanda/airflow/dags/weatherapi_test.py
Traceback (most recent call last):
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/sunanda/airflow/dags/weatherapi_test.py", line 13, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-03-25T14:05:46.984-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:05:47.178-0400] {processor.py:175} INFO - Processing /Users/sunanda/airflow/dags/weatherapi_test.py took 0.232 seconds
[2023-03-25T14:08:49.906-0400] {processor.py:153} INFO - Started process (PID=8013) to work on /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:08:49.909-0400] {processor.py:743} INFO - Processing file /Users/sunanda/airflow/dags/weatherapi_test.py for tasks to queue
[2023-03-25T14:08:49.909-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:08:49.909-0400] {dagbag.py:532} INFO - Filling up the DagBag from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:08:49.948-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:08:49.935-0400] {dagbag.py:341} ERROR - Failed to import: /Users/sunanda/airflow/dags/weatherapi_test.py
Traceback (most recent call last):
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/sunanda/airflow/dags/weatherapi_test.py", line 119, in <module>
    python_operator = PythonOperator(task_id="print message", python_callable=print_message, dag=dag)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/operators/python.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 753, in __init__
    validate_key(task_id)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'print message' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-03-25T14:08:49.948-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:08:50.141-0400] {processor.py:175} INFO - Processing /Users/sunanda/airflow/dags/weatherapi_test.py took 0.235 seconds
[2023-03-25T14:10:21.598-0400] {processor.py:153} INFO - Started process (PID=8164) to work on /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:10:21.600-0400] {processor.py:743} INFO - Processing file /Users/sunanda/airflow/dags/weatherapi_test.py for tasks to queue
[2023-03-25T14:10:21.600-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:10:21.600-0400] {dagbag.py:532} INFO - Filling up the DagBag from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:10:21.637-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:10:21.625-0400] {dagbag.py:341} ERROR - Failed to import: /Users/sunanda/airflow/dags/weatherapi_test.py
Traceback (most recent call last):
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/sunanda/airflow/dags/weatherapi_test.py", line 134, in <module>
    spark_submit = SparkSubmitOperator(
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 124, in __init__
    super().__init__(**kwargs)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 742, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: spark_submit_task). Invalid arguments were:
**kwargs: {'executer_cores': 1, 'num_executers': 1, 'executer_memory': 'lg'}
[2023-03-25T14:10:21.637-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:10:21.837-0400] {processor.py:175} INFO - Processing /Users/sunanda/airflow/dags/weatherapi_test.py took 0.240 seconds
[2023-03-25T14:10:28.425-0400] {processor.py:153} INFO - Started process (PID=8176) to work on /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:10:28.428-0400] {processor.py:743} INFO - Processing file /Users/sunanda/airflow/dags/weatherapi_test.py for tasks to queue
[2023-03-25T14:10:28.428-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:10:28.428-0400] {dagbag.py:532} INFO - Filling up the DagBag from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:10:28.464-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:10:28.452-0400] {dagbag.py:341} ERROR - Failed to import: /Users/sunanda/airflow/dags/weatherapi_test.py
Traceback (most recent call last):
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/sunanda/airflow/dags/weatherapi_test.py", line 134, in <module>
    spark_submit = SparkSubmitOperator(
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 124, in __init__
    super().__init__(**kwargs)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 742, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: spark_submit_task). Invalid arguments were:
**kwargs: {'executer_cores': 1, 'num_executers': 1, 'executer_memory': 'lg'}
[2023-03-25T14:10:28.464-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:10:28.663-0400] {processor.py:175} INFO - Processing /Users/sunanda/airflow/dags/weatherapi_test.py took 0.238 seconds
[2023-03-25T14:11:44.367-0400] {processor.py:153} INFO - Started process (PID=8305) to work on /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:11:44.369-0400] {processor.py:743} INFO - Processing file /Users/sunanda/airflow/dags/weatherapi_test.py for tasks to queue
[2023-03-25T14:11:44.370-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:11:44.370-0400] {dagbag.py:532} INFO - Filling up the DagBag from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:11:44.405-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:11:44.394-0400] {dagbag.py:341} ERROR - Failed to import: /Users/sunanda/airflow/dags/weatherapi_test.py
Traceback (most recent call last):
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/sunanda/airflow/dags/weatherapi_test.py", line 134, in <module>
    spark_submit = SparkSubmitOperator(
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 124, in __init__
    super().__init__(**kwargs)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 742, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: spark_submit_task). Invalid arguments were:
**kwargs: {'executer_cores': 1, 'num_executers': 1, 'executer_memory': 'lg'}
[2023-03-25T14:11:44.405-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:11:44.600-0400] {processor.py:175} INFO - Processing /Users/sunanda/airflow/dags/weatherapi_test.py took 0.233 seconds
[2023-03-25T14:12:29.566-0400] {processor.py:153} INFO - Started process (PID=8396) to work on /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:12:29.569-0400] {processor.py:743} INFO - Processing file /Users/sunanda/airflow/dags/weatherapi_test.py for tasks to queue
[2023-03-25T14:12:29.569-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:12:29.569-0400] {dagbag.py:532} INFO - Filling up the DagBag from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:12:29.607-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:12:29.595-0400] {dagbag.py:341} ERROR - Failed to import: /Users/sunanda/airflow/dags/weatherapi_test.py
Traceback (most recent call last):
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/sunanda/airflow/dags/weatherapi_test.py", line 134, in <module>
    spark_submit = SparkSubmitOperator(
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 124, in __init__
    super().__init__(**kwargs)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 742, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: spark_submit_task). Invalid arguments were:
**kwargs: {'executer_cores': 1, 'num_executers': 1, 'executer_memory': 'lg'}
[2023-03-25T14:12:29.607-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:12:29.800-0400] {processor.py:175} INFO - Processing /Users/sunanda/airflow/dags/weatherapi_test.py took 0.235 seconds
[2023-03-25T14:13:13.071-0400] {processor.py:153} INFO - Started process (PID=8462) to work on /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:13:13.073-0400] {processor.py:743} INFO - Processing file /Users/sunanda/airflow/dags/weatherapi_test.py for tasks to queue
[2023-03-25T14:13:13.073-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:13:13.073-0400] {dagbag.py:532} INFO - Filling up the DagBag from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:13:13.109-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:13:13.099-0400] {dagbag.py:341} ERROR - Failed to import: /Users/sunanda/airflow/dags/weatherapi_test.py
Traceback (most recent call last):
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/sunanda/airflow/dags/weatherapi_test.py", line 134, in <module>
    spark_submit = SparkSubmitOperator(
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 124, in __init__
    super().__init__(**kwargs)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 742, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: spark_submit_task). Invalid arguments were:
**kwargs: {'executer_cores': 1, 'num_executers': 1, 'executer_memory': 'lg'}
[2023-03-25T14:13:13.109-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:13:13.309-0400] {processor.py:175} INFO - Processing /Users/sunanda/airflow/dags/weatherapi_test.py took 0.239 seconds
[2023-03-25T14:13:56.901-0400] {processor.py:153} INFO - Started process (PID=8531) to work on /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:13:56.903-0400] {processor.py:743} INFO - Processing file /Users/sunanda/airflow/dags/weatherapi_test.py for tasks to queue
[2023-03-25T14:13:56.903-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:13:56.903-0400] {dagbag.py:532} INFO - Filling up the DagBag from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:13:56.943-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:13:56.932-0400] {dagbag.py:341} ERROR - Failed to import: /Users/sunanda/airflow/dags/weatherapi_test.py
Traceback (most recent call last):
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/sunanda/airflow/dags/weatherapi_test.py", line 134, in <module>
    spark_submit = SparkSubmitOperator(
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 124, in __init__
    super().__init__(**kwargs)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 742, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: spark_submit_task). Invalid arguments were:
**kwargs: {'executer_cores': 1, 'num_executers': 1, 'executer_memory': 'lg'}
[2023-03-25T14:13:56.943-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:13:57.144-0400] {processor.py:175} INFO - Processing /Users/sunanda/airflow/dags/weatherapi_test.py took 0.244 seconds
[2023-03-25T14:14:38.317-0400] {processor.py:153} INFO - Started process (PID=8596) to work on /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:14:38.320-0400] {processor.py:743} INFO - Processing file /Users/sunanda/airflow/dags/weatherapi_test.py for tasks to queue
[2023-03-25T14:14:38.320-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:14:38.320-0400] {dagbag.py:532} INFO - Filling up the DagBag from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:14:38.357-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:14:38.346-0400] {dagbag.py:341} ERROR - Failed to import: /Users/sunanda/airflow/dags/weatherapi_test.py
Traceback (most recent call last):
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/sunanda/airflow/dags/weatherapi_test.py", line 134, in <module>
    spark_submit = SparkSubmitOperator(
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 124, in __init__
    super().__init__(**kwargs)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 742, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: spark_submit_task). Invalid arguments were:
**kwargs: {'executer_cores': 1, 'num_executers': 1, 'executer_memory': 'lg'}
[2023-03-25T14:14:38.357-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:14:38.550-0400] {processor.py:175} INFO - Processing /Users/sunanda/airflow/dags/weatherapi_test.py took 0.234 seconds
[2023-03-25T14:15:21.973-0400] {processor.py:153} INFO - Started process (PID=8664) to work on /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:15:21.975-0400] {processor.py:743} INFO - Processing file /Users/sunanda/airflow/dags/weatherapi_test.py for tasks to queue
[2023-03-25T14:15:21.975-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:15:21.975-0400] {dagbag.py:532} INFO - Filling up the DagBag from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:15:22.014-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:15:22.002-0400] {dagbag.py:341} ERROR - Failed to import: /Users/sunanda/airflow/dags/weatherapi_test.py
Traceback (most recent call last):
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/sunanda/airflow/dags/weatherapi_test.py", line 134, in <module>
    spark_submit = SparkSubmitOperator(
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 124, in __init__
    super().__init__(**kwargs)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 742, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: spark_submit_task). Invalid arguments were:
**kwargs: {'executer_cores': 1, 'num_executers': 1, 'executer_memory': 'lg'}
[2023-03-25T14:15:22.014-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:15:22.218-0400] {processor.py:175} INFO - Processing /Users/sunanda/airflow/dags/weatherapi_test.py took 0.246 seconds
[2023-03-25T14:16:08.134-0400] {processor.py:153} INFO - Started process (PID=8734) to work on /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:16:08.136-0400] {processor.py:743} INFO - Processing file /Users/sunanda/airflow/dags/weatherapi_test.py for tasks to queue
[2023-03-25T14:16:08.136-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:16:08.136-0400] {dagbag.py:532} INFO - Filling up the DagBag from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:16:08.172-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:16:08.161-0400] {dagbag.py:341} ERROR - Failed to import: /Users/sunanda/airflow/dags/weatherapi_test.py
Traceback (most recent call last):
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/sunanda/airflow/dags/weatherapi_test.py", line 134, in <module>
    spark_submit = SparkSubmitOperator(
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 124, in __init__
    super().__init__(**kwargs)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 742, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: spark_submit_task). Invalid arguments were:
**kwargs: {'executer_cores': 1, 'num_executers': 1, 'executer_memory': 'lg'}
[2023-03-25T14:16:08.172-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:16:08.374-0400] {processor.py:175} INFO - Processing /Users/sunanda/airflow/dags/weatherapi_test.py took 0.240 seconds
[2023-03-25T14:16:54.227-0400] {processor.py:153} INFO - Started process (PID=8806) to work on /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:16:54.230-0400] {processor.py:743} INFO - Processing file /Users/sunanda/airflow/dags/weatherapi_test.py for tasks to queue
[2023-03-25T14:16:54.230-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:16:54.230-0400] {dagbag.py:532} INFO - Filling up the DagBag from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:16:54.267-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:16:54.255-0400] {dagbag.py:341} ERROR - Failed to import: /Users/sunanda/airflow/dags/weatherapi_test.py
Traceback (most recent call last):
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/sunanda/airflow/dags/weatherapi_test.py", line 132, in <module>
    spark_submit = SparkSubmitOperator(
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 124, in __init__
    super().__init__(**kwargs)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 742, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: spark_submit_task). Invalid arguments were:
**kwargs: {'executer_cores': 1, 'num_executers': 1, 'executer_memory': 'lg'}
[2023-03-25T14:16:54.267-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:16:54.468-0400] {processor.py:175} INFO - Processing /Users/sunanda/airflow/dags/weatherapi_test.py took 0.241 seconds
[2023-03-25T14:17:39.743-0400] {processor.py:153} INFO - Started process (PID=8879) to work on /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:17:39.745-0400] {processor.py:743} INFO - Processing file /Users/sunanda/airflow/dags/weatherapi_test.py for tasks to queue
[2023-03-25T14:17:39.745-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:17:39.745-0400] {dagbag.py:532} INFO - Filling up the DagBag from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:17:39.785-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:17:39.773-0400] {dagbag.py:341} ERROR - Failed to import: /Users/sunanda/airflow/dags/weatherapi_test.py
Traceback (most recent call last):
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/sunanda/airflow/dags/weatherapi_test.py", line 132, in <module>
    spark_submit = SparkSubmitOperator(
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 124, in __init__
    super().__init__(**kwargs)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 742, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: spark_submit_task). Invalid arguments were:
**kwargs: {'executer_cores': 1, 'num_executers': 1, 'executer_memory': 'lg'}
[2023-03-25T14:17:39.785-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:17:39.991-0400] {processor.py:175} INFO - Processing /Users/sunanda/airflow/dags/weatherapi_test.py took 0.248 seconds
[2023-03-25T14:18:25.166-0400] {processor.py:153} INFO - Started process (PID=8972) to work on /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:18:25.168-0400] {processor.py:743} INFO - Processing file /Users/sunanda/airflow/dags/weatherapi_test.py for tasks to queue
[2023-03-25T14:18:25.168-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:18:25.168-0400] {dagbag.py:532} INFO - Filling up the DagBag from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:18:25.207-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:18:25.195-0400] {dagbag.py:341} ERROR - Failed to import: /Users/sunanda/airflow/dags/weatherapi_test.py
Traceback (most recent call last):
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/sunanda/airflow/dags/weatherapi_test.py", line 132, in <module>
    spark_submit = SparkSubmitOperator(
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 124, in __init__
    super().__init__(**kwargs)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 742, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: spark_submit_task). Invalid arguments were:
**kwargs: {'executer_cores': 1, 'num_executers': 1, 'executer_memory': 'lg'}
[2023-03-25T14:18:25.207-0400] {processor.py:755} WARNING - No viable dags retrieved from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:18:25.405-0400] {processor.py:175} INFO - Processing /Users/sunanda/airflow/dags/weatherapi_test.py took 0.239 seconds
[2023-03-25T14:19:43.725-0400] {processor.py:153} INFO - Started process (PID=9097) to work on /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:19:43.727-0400] {processor.py:743} INFO - Processing file /Users/sunanda/airflow/dags/weatherapi_test.py for tasks to queue
[2023-03-25T14:19:43.727-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:19:43.727-0400] {dagbag.py:532} INFO - Filling up the DagBag from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:19:43.757-0400] {processor.py:753} INFO - DAG(s) dict_keys(['api_dag']) retrieved from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:19:44.015-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:19:44.014-0400] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-25T14:19:44.022-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:19:44.022-0400] {dag.py:3440} INFO - Setting next_dagrun for api_dag to 2023-03-24T00:00:00+00:00, run_after=2023-03-25T00:00:00+00:00
[2023-03-25T14:19:44.030-0400] {processor.py:175} INFO - Processing /Users/sunanda/airflow/dags/weatherapi_test.py took 0.306 seconds
[2023-03-25T14:20:53.516-0400] {processor.py:153} INFO - Started process (PID=9290) to work on /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:20:53.519-0400] {processor.py:743} INFO - Processing file /Users/sunanda/airflow/dags/weatherapi_test.py for tasks to queue
[2023-03-25T14:20:53.520-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:20:53.520-0400] {dagbag.py:532} INFO - Filling up the DagBag from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:20:53.553-0400] {processor.py:753} INFO - DAG(s) dict_keys(['api_dag']) retrieved from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:20:53.795-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:20:53.795-0400] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-25T14:20:53.803-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:20:53.803-0400] {dag.py:3440} INFO - Setting next_dagrun for api_dag to 2023-03-25T00:00:00+00:00, run_after=2023-03-26T00:00:00+00:00
[2023-03-25T14:20:53.810-0400] {processor.py:175} INFO - Processing /Users/sunanda/airflow/dags/weatherapi_test.py took 0.294 seconds
[2023-03-25T14:21:56.528-0400] {processor.py:153} INFO - Started process (PID=9359) to work on /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:21:56.531-0400] {processor.py:743} INFO - Processing file /Users/sunanda/airflow/dags/weatherapi_test.py for tasks to queue
[2023-03-25T14:21:56.532-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:21:56.532-0400] {dagbag.py:532} INFO - Filling up the DagBag from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:21:56.569-0400] {processor.py:753} INFO - DAG(s) dict_keys(['api_dag']) retrieved from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:21:56.816-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:21:56.816-0400] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-25T14:21:56.823-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:21:56.823-0400] {dag.py:3440} INFO - Setting next_dagrun for api_dag to 2023-03-25T00:00:00+00:00, run_after=2023-03-26T00:00:00+00:00
[2023-03-25T14:21:56.831-0400] {processor.py:175} INFO - Processing /Users/sunanda/airflow/dags/weatherapi_test.py took 0.303 seconds
[2023-03-25T14:42:45.961-0400] {processor.py:153} INFO - Started process (PID=10682) to work on /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:42:45.964-0400] {processor.py:743} INFO - Processing file /Users/sunanda/airflow/dags/weatherapi_test.py for tasks to queue
[2023-03-25T14:42:45.964-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:42:45.964-0400] {dagbag.py:532} INFO - Filling up the DagBag from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:42:45.999-0400] {processor.py:753} INFO - DAG(s) dict_keys(['api_dag']) retrieved from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:42:46.233-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:42:46.233-0400] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-25T14:42:46.241-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:42:46.241-0400] {dag.py:3440} INFO - Setting next_dagrun for api_dag to 2023-03-25T00:00:00+00:00, run_after=2023-03-26T00:00:00+00:00
[2023-03-25T14:42:46.248-0400] {processor.py:175} INFO - Processing /Users/sunanda/airflow/dags/weatherapi_test.py took 0.287 seconds
[2023-03-25T14:44:03.199-0400] {processor.py:153} INFO - Started process (PID=10830) to work on /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:44:03.201-0400] {processor.py:743} INFO - Processing file /Users/sunanda/airflow/dags/weatherapi_test.py for tasks to queue
[2023-03-25T14:44:03.202-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:44:03.201-0400] {dagbag.py:532} INFO - Filling up the DagBag from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:44:03.231-0400] {processor.py:753} INFO - DAG(s) dict_keys(['api_dag']) retrieved from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:44:03.469-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:44:03.469-0400] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-25T14:44:03.477-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:44:03.476-0400] {dag.py:3440} INFO - Setting next_dagrun for api_dag to 2023-03-25T00:00:00+00:00, run_after=2023-03-26T00:00:00+00:00
[2023-03-25T14:44:03.484-0400] {processor.py:175} INFO - Processing /Users/sunanda/airflow/dags/weatherapi_test.py took 0.285 seconds
[2023-03-25T14:44:50.901-0400] {processor.py:153} INFO - Started process (PID=10910) to work on /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:44:50.904-0400] {processor.py:743} INFO - Processing file /Users/sunanda/airflow/dags/weatherapi_test.py for tasks to queue
[2023-03-25T14:44:50.904-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:44:50.904-0400] {dagbag.py:532} INFO - Filling up the DagBag from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:44:50.937-0400] {processor.py:753} INFO - DAG(s) dict_keys(['api_dag']) retrieved from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:44:51.194-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:44:51.194-0400] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-25T14:44:51.202-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:44:51.202-0400] {dag.py:3440} INFO - Setting next_dagrun for api_dag to 2023-03-25T00:00:00+00:00, run_after=2023-03-26T00:00:00+00:00
[2023-03-25T14:44:51.210-0400] {processor.py:175} INFO - Processing /Users/sunanda/airflow/dags/weatherapi_test.py took 0.309 seconds
[2023-03-25T14:45:34.683-0400] {processor.py:153} INFO - Started process (PID=10977) to work on /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:45:34.686-0400] {processor.py:743} INFO - Processing file /Users/sunanda/airflow/dags/weatherapi_test.py for tasks to queue
[2023-03-25T14:45:34.686-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:45:34.686-0400] {dagbag.py:532} INFO - Filling up the DagBag from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:45:34.715-0400] {processor.py:753} INFO - DAG(s) dict_keys(['api_dag']) retrieved from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:45:34.950-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:45:34.949-0400] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-25T14:45:34.957-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:45:34.957-0400] {dag.py:3440} INFO - Setting next_dagrun for api_dag to 2023-03-25T00:00:00+00:00, run_after=2023-03-26T00:00:00+00:00
[2023-03-25T14:45:34.965-0400] {processor.py:175} INFO - Processing /Users/sunanda/airflow/dags/weatherapi_test.py took 0.282 seconds
[2023-03-25T14:46:19.207-0400] {processor.py:153} INFO - Started process (PID=11048) to work on /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:46:19.210-0400] {processor.py:743} INFO - Processing file /Users/sunanda/airflow/dags/weatherapi_test.py for tasks to queue
[2023-03-25T14:46:19.210-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:46:19.210-0400] {dagbag.py:532} INFO - Filling up the DagBag from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:46:19.243-0400] {processor.py:753} INFO - DAG(s) dict_keys(['api_dag']) retrieved from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:46:19.486-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:46:19.486-0400] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-25T14:46:19.494-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:46:19.494-0400] {dag.py:3440} INFO - Setting next_dagrun for api_dag to 2023-03-25T00:00:00+00:00, run_after=2023-03-26T00:00:00+00:00
[2023-03-25T14:46:19.502-0400] {processor.py:175} INFO - Processing /Users/sunanda/airflow/dags/weatherapi_test.py took 0.295 seconds
[2023-03-25T14:47:06.108-0400] {processor.py:153} INFO - Started process (PID=11120) to work on /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:47:06.112-0400] {processor.py:743} INFO - Processing file /Users/sunanda/airflow/dags/weatherapi_test.py for tasks to queue
[2023-03-25T14:47:06.112-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:47:06.112-0400] {dagbag.py:532} INFO - Filling up the DagBag from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:47:06.144-0400] {processor.py:753} INFO - DAG(s) dict_keys(['api_dag']) retrieved from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:47:06.405-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:47:06.405-0400] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-25T14:47:06.413-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:47:06.413-0400] {dag.py:3440} INFO - Setting next_dagrun for api_dag to 2023-03-25T00:00:00+00:00, run_after=2023-03-26T00:00:00+00:00
[2023-03-25T14:47:06.420-0400] {processor.py:175} INFO - Processing /Users/sunanda/airflow/dags/weatherapi_test.py took 0.312 seconds
[2023-03-25T14:47:51.409-0400] {processor.py:153} INFO - Started process (PID=11190) to work on /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:47:51.411-0400] {processor.py:743} INFO - Processing file /Users/sunanda/airflow/dags/weatherapi_test.py for tasks to queue
[2023-03-25T14:47:51.412-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:47:51.412-0400] {dagbag.py:532} INFO - Filling up the DagBag from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:47:51.439-0400] {processor.py:753} INFO - DAG(s) dict_keys(['api_dag']) retrieved from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T14:47:51.665-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:47:51.665-0400] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-25T14:47:51.673-0400] {logging_mixin.py:137} INFO - [2023-03-25T14:47:51.673-0400] {dag.py:3440} INFO - Setting next_dagrun for api_dag to 2023-03-25T00:00:00+00:00, run_after=2023-03-26T00:00:00+00:00
[2023-03-25T14:47:51.680-0400] {processor.py:175} INFO - Processing /Users/sunanda/airflow/dags/weatherapi_test.py took 0.271 seconds
[2023-03-25T16:12:17.066-0400] {processor.py:153} INFO - Started process (PID=17913) to work on /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T16:12:17.069-0400] {processor.py:743} INFO - Processing file /Users/sunanda/airflow/dags/weatherapi_test.py for tasks to queue
[2023-03-25T16:12:17.069-0400] {logging_mixin.py:137} INFO - [2023-03-25T16:12:17.069-0400] {dagbag.py:532} INFO - Filling up the DagBag from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T16:12:17.103-0400] {processor.py:753} INFO - DAG(s) dict_keys(['api_dag']) retrieved from /Users/sunanda/airflow/dags/weatherapi_test.py
[2023-03-25T16:12:17.368-0400] {logging_mixin.py:137} INFO - [2023-03-25T16:12:17.367-0400] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-25T16:12:17.375-0400] {logging_mixin.py:137} INFO - [2023-03-25T16:12:17.375-0400] {dag.py:3440} INFO - Setting next_dagrun for api_dag to 2023-03-25T00:00:00+00:00, run_after=2023-03-26T00:00:00+00:00
[2023-03-25T16:12:17.382-0400] {processor.py:175} INFO - Processing /Users/sunanda/airflow/dags/weatherapi_test.py took 0.317 seconds
