[2023-03-22T16:17:48.684-0400] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: api_dag.is_api_active manual__2023-03-22T19:06:03.876863+00:00 [queued]>
[2023-03-22T16:17:48.689-0400] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: api_dag.is_api_active manual__2023-03-22T19:06:03.876863+00:00 [queued]>
[2023-03-22T16:17:48.689-0400] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T16:17:48.689-0400] {taskinstance.py:1280} INFO - Starting attempt 9 of 1
[2023-03-22T16:17:48.689-0400] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T16:17:48.701-0400] {taskinstance.py:1300} INFO - Executing <Task(HttpSensor): is_api_active> on 2023-03-22 19:06:03.876863+00:00
[2023-03-22T16:17:48.704-0400] {standard_task_runner.py:55} INFO - Started process 74808 to run task
[2023-03-22T16:17:48.707-0400] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'api_dag', 'is_api_active', 'manual__2023-03-22T19:06:03.876863+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/weatherapi_test.py', '--cfg-path', '/var/folders/71/zhs_yc7n05l7c97rnhn92bb80000gn/T/tmpxt2l49wv']
[2023-03-22T16:17:48.707-0400] {standard_task_runner.py:83} INFO - Job 34: Subtask is_api_active
[2023-03-22T16:17:48.725-0400] {task_command.py:388} INFO - Running <TaskInstance: api_dag.is_api_active manual__2023-03-22T19:06:03.876863+00:00 [running]> on host sunandas-laptop.local
[2023-03-22T16:17:48.746-0400] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=api_dag
AIRFLOW_CTX_TASK_ID=is_api_active
AIRFLOW_CTX_EXECUTION_DATE=2023-03-22T19:06:03.876863+00:00
AIRFLOW_CTX_TRY_NUMBER=9
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-22T19:06:03.876863+00:00
[2023-03-22T16:17:48.747-0400] {http.py:122} INFO - Poking: weather?q=Monroe,GA,US&units=standard&appid=94ca56afa3eee20f7100985fdfe682aa
[2023-03-22T16:17:48.750-0400] {base.py:73} INFO - Using connection ID 'my_api_connection' for task execution.
[2023-03-22T16:20:49.718-0400] {local_task_job.py:255} WARNING - Recorded pid 75025 does not match the current pid 74808
[2023-03-22T16:20:49.723-0400] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 74808. PIDs of all processes in the group: [74808]
[2023-03-22T16:20:49.723-0400] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 74808
[2023-03-22T16:21:49.738-0400] {process_utils.py:147} WARNING - process psutil.Process(pid=74808, name='Python', status='running', started='16:17:48') did not respond to SIGTERM. Trying SIGKILL
[2023-03-22T16:21:49.739-0400] {process_utils.py:84} INFO - Sending the signal Signals.SIGKILL to group 74808
[2023-03-22T16:21:49.743-0400] {process_utils.py:79} INFO - Process psutil.Process(pid=74808, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='16:17:48') (74808) terminated with exit code Negsignal.SIGKILL
[2023-03-22T16:21:49.744-0400] {standard_task_runner.py:168} ERROR - Job 38 was killed before it finished (likely due to running out of memory)
