[2023-03-26T00:39:24.620-0400] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_dag.is_api_active scheduled__2023-03-25T00:00:00+00:00 [queued]>
[2023-03-26T00:39:24.633-0400] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_dag.is_api_active scheduled__2023-03-25T00:00:00+00:00 [queued]>
[2023-03-26T00:39:24.633-0400] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-26T00:39:24.634-0400] {taskinstance.py:1283} INFO - Starting attempt 8 of 1
[2023-03-26T00:39:24.634-0400] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-26T00:39:24.638-0400] {taskinstance.py:1303} INFO - Executing <Task(HttpSensor): is_api_active> on 2023-03-25 00:00:00+00:00
[2023-03-26T00:39:24.641-0400] {standard_task_runner.py:55} INFO - Started process 36798 to run task
[2023-03-26T00:39:24.645-0400] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'api_dag', 'is_api_active', 'scheduled__2023-03-25T00:00:00+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/weatherapi_test.py', '--cfg-path', '/var/folders/71/zhs_yc7n05l7c97rnhn92bb80000gn/T/tmpfsmobksy']
[2023-03-26T00:39:24.646-0400] {standard_task_runner.py:83} INFO - Job 133: Subtask is_api_active
[2023-03-26T00:39:24.747-0400] {task_command.py:388} INFO - Running <TaskInstance: api_dag.is_api_active scheduled__2023-03-25T00:00:00+00:00 [running]> on host sunandas-laptop.hsd1.ga.comcast.net
[2023-03-26T00:39:24.773-0400] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=api_dag
AIRFLOW_CTX_TASK_ID=is_api_active
AIRFLOW_CTX_EXECUTION_DATE=2023-03-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=8
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-25T00:00:00+00:00
[2023-03-26T00:39:24.774-0400] {http.py:122} INFO - Poking: weather?q=Atlanta,Georgia,US&units=standard&appid=94ca56afa3eee20f7100985fdfe682aa
[2023-03-26T00:39:24.776-0400] {base.py:73} INFO - Using connection ID 'my_api_connection' for task execution.
[2023-03-26T00:40:45.155-0400] {local_task_job.py:259} WARNING - Recorded pid 36892 does not match the current pid 36798
[2023-03-26T00:40:45.162-0400] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 36798. PIDs of all processes in the group: [36798]
[2023-03-26T00:40:45.162-0400] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 36798
[2023-03-26T00:41:45.188-0400] {process_utils.py:147} WARNING - process psutil.Process(pid=36798, name='Python', status='running', started='00:39:24') did not respond to SIGTERM. Trying SIGKILL
[2023-03-26T00:41:45.191-0400] {process_utils.py:84} INFO - Sending the signal Signals.SIGKILL to group 36798
[2023-03-26T00:41:45.199-0400] {process_utils.py:79} INFO - Process psutil.Process(pid=36798, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='00:39:24') (36798) terminated with exit code Negsignal.SIGKILL
[2023-03-26T00:41:45.200-0400] {standard_task_runner.py:168} ERROR - Job 136 was killed before it finished (likely due to running out of memory)
