[2023-03-21T16:11:45.351-0400] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: api_dag.get_posts scheduled__2023-03-19T00:00:00+00:00 [queued]>
[2023-03-21T16:11:45.356-0400] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: api_dag.get_posts scheduled__2023-03-19T00:00:00+00:00 [queued]>
[2023-03-21T16:11:45.356-0400] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T16:11:45.356-0400] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-21T16:11:45.356-0400] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T16:11:45.360-0400] {taskinstance.py:1300} INFO - Executing <Task(SimpleHttpOperator): get_posts> on 2023-03-19 00:00:00+00:00
[2023-03-21T16:11:45.362-0400] {standard_task_runner.py:55} INFO - Started process 41452 to run task
[2023-03-21T16:11:45.365-0400] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'api_dag', 'get_posts', 'scheduled__2023-03-19T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/weatherapi_test.py', '--cfg-path', '/var/folders/71/zhs_yc7n05l7c97rnhn92bb80000gn/T/tmp5r_iyd28']
[2023-03-21T16:11:45.365-0400] {standard_task_runner.py:83} INFO - Job 9: Subtask get_posts
[2023-03-21T16:11:45.400-0400] {task_command.py:388} INFO - Running <TaskInstance: api_dag.get_posts scheduled__2023-03-19T00:00:00+00:00 [running]> on host sunandas-laptop.local
[2023-03-21T16:11:45.421-0400] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=api_dag
AIRFLOW_CTX_TASK_ID=get_posts
AIRFLOW_CTX_EXECUTION_DATE=2023-03-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-19T00:00:00+00:00
[2023-03-21T16:11:45.421-0400] {http.py:123} INFO - Calling HTTP method
[2023-03-21T16:11:45.424-0400] {base.py:73} INFO - Using connection ID 'my_api_connection' for task execution.
[2023-03-21T19:16:40.215-0400] {local_task_job.py:192} ERROR - Heartbeat time limit exceeded!
[2023-03-21T19:16:40.349-0400] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 41452. PIDs of all processes in the group: [41452]
[2023-03-21T19:16:40.349-0400] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 41452
[2023-03-21T20:23:08.274-0400] {process_utils.py:147} WARNING - process psutil.Process(pid=41452, name='Python', status='running', started='16:11:45') did not respond to SIGTERM. Trying SIGKILL
[2023-03-21T20:23:08.276-0400] {process_utils.py:84} INFO - Sending the signal Signals.SIGKILL to group 41452
[2023-03-21T20:23:08.280-0400] {process_utils.py:79} INFO - Process psutil.Process(pid=41452, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='16:11:45') (41452) terminated with exit code Negsignal.SIGKILL
[2023-03-21T20:23:08.280-0400] {standard_task_runner.py:168} ERROR - Job 9 was killed before it finished (likely due to running out of memory)
